# Generated by Django 2.1.2 on 2018-10-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtuacaoProfissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresas', models.TextField()),
                ('areas_atuacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('ic', 'ic'), ('iti', 'iti'), ('unasus', 'unasus')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('perfil_aluno', models.TextField()),
                ('grade_curricular', models.FileField(upload_to='')),
                ('diferenciais', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('instituicao', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socio_culturais', models.TextField()),
                ('humanitarias', models.TextField()),
                ('tecnicas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesInfobio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('perfil_aluno', models.TextField()),
                ('grade_curricular', models.FileField(upload_to='')),
                ('diferenciais', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesUfcspa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('infraestrutura', models.TextField()),
                ('cursos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('orientador', models.CharField(max_length=50)),
                ('participantes', models.TextField()),
                ('areas', models.TextField()),
            ],
        ),
    ]
