# Generated by Django 2.1.2 on 2018-10-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=200)),
                ('corpo', models.CharField(max_length=5000)),
                ('autor', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
                ('data_expiracao', models.DateField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AtuacaoProfissional',
        ),
        migrations.DeleteModel(
            name='Bolsa',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Estagio',
        ),
        migrations.DeleteModel(
            name='Habilidades',
        ),
        migrations.DeleteModel(
            name='InformacoesInfobio',
        ),
        migrations.DeleteModel(
            name='InformacoesUfcspa',
        ),
        migrations.DeleteModel(
            name='ProjetoPesquisa',
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Secao'),
        ),
    ]
