# Generated by Django 2.1.2 on 2018-10-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20181009_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('change_date', models.DateField(auto_now=True)),
                ('expiration_date', models.DateField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Category')),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='id_secao',
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='id_categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Conteudo',
        ),
        migrations.DeleteModel(
            name='Secao',
        ),
        migrations.AddField(
            model_name='category',
            name='id_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Section'),
        ),
    ]
