# Generated by Django 2.1.2 on 2018-11-08 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20181105_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is', models.TextField()),
                ('acting', models.TextField()),
                ('curricular_matrix', models.TextField()),
                ('knowledge', models.TextField()),
            ],
            options={
                'verbose_name': 'Sobre',
                'verbose_name_plural': 'Sobre',
            },
        ),
        migrations.CreateModel(
            name='AreaBigCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Área mais genérica',
                'verbose_name_plural': 'Área mais genérica',
            },
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('projects', models.TextField()),
                ('health_informatics', models.TextField()),
                ('bionformatics', models.TextField()),
                ('contact', models.TextField()),
            ],
            options={
                'verbose_name': 'Página inicial',
                'verbose_name_plural': 'Página inicial',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('institution', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
            },
        ),
        migrations.CreateModel(
            name='SpecificArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('related_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.AreaBigCategory')),
            ],
            options={
                'verbose_name': 'Área específica',
                'verbose_name_plural': 'Área específica',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='id_section',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='content',
            name='id_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
