# Generated by Django 2.1.2 on 2018-11-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20181105_2001'),
        ('cms', '0013_auto_20181108_1301'),
    ]

    operations = [
    ]
