# Generated by Django 2.1.2 on 2018-11-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_merge_20181108_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-approved', '-created_date'], 'verbose_name': 'Oportunidade', 'verbose_name_plural': 'Oportunidades'},
        ),
    ]
