# Generated by Django 2.1.2 on 2018-11-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20181109_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='url_details',
            field=models.CharField(default='', max_length=500, verbose_name='Link com mais detalhes'),
        ),
    ]
